version: '3.8'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
      - ./uploads:/usr/src/app/uploads  # Map uploads directory for file storage
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:4000  # Configure API URL for React app
